<div>
    <table>
        <thead>
        <tr><th>Sku</th><th>Weight</th></tr>
        </thead>
        <tbody>
        <?php
        $collection = $block->getAllProductsLouiseCat();
        foreach ( $collection as $product ){
            print '<tr><td>'. $product->getSku().'</td><td>'.$product->getWeight().'</td><tr>';
        }
        ?>
        </tbody>
    </table>
</div>
<div>
    <?php
    echo __('There are objects')
    ?>
    <table>
        <thead>
        <tr><th>title</th><th>content</th></tr>
        </thead>
        <tbody>
    <?php
    $collection = $block->getAllObject();
    foreach ( $collection as $objet ){
        print '<tr><td>'. $objet->getTitleTest().'</td><td>'. $objet->getContent().'</td><tr>';
    }
    ?>
        </tbody>
    </table>
</div>
<div>
    <h2>Second titre de la page</h2>
    <p>
        Super ça marche bien
    </p>
</div>
<div>
    <p>VARIABLE DE L'ADMIN</p>
    <?php
        print $this->scopeConfig->getValue('louisefirstmodule/general/option', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);

    ?>
    <p>Fin VARIABLE</p>
</div>